name: Azure App Service - contentfulappjs(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - dependabot/npm_and_yarn/ini-1.3.7

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses:  actions/checkout@v2
      with:
        ref: 'dependabot/npm_and_yarn/ini-1.3.7'

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

  deploy:
     runs-on: ubuntu-latest
     environment:
        name: Development
     steps:       
       - name: Run Azure webapp deploy action using publish profile credentials
         uses: azure/webapps-deploy@v2
         with:
            app-name: contentfulappjs
            slot-name: Production
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_79E8EAAAACD14386986342D48827EAFA }}
            package: .